on:
  schedule:
    - cron: '1/2 * * * *'
  workflow_dispatch:
    inputs:
      url:
        description: "Base URL"
        required: true
        default: "https://test-dispatch.com"

jobs:
  featuretests:
    runs-on: ubuntu-latest
    env:
      CI: true
      DEFAULT_URL: "https://test.com"
    steps:
      - name: Set the variables
        env:
          DEFAULT_URL: 'https://test.com'
        run: echo "BASE_URL=${{ github.event.inputs.url || env.DEFAULT_URL }}" >> $GITHUB_ENV

      - name: Print some text
        run: echo "$BASE_URL"
