on:
  workflow_dispatch:
    inputs:
      url:
        description: "Base URL"
        required: true
        default: "https://test-dispatch.com"

jobs:
  featuretests:
    runs-on: ubuntu-latest
    env:
      CI: true
      DEFAULT_URL: "https://test.com"
    steps:
      - name: Determine Base URL
        if: ${{ github.event.inputs.url }}
        run: |
          $DEFAULT_URL = ${{ github.event.inputs.url }}
          echo $DEFAULT_URL
