on:
  workflow_dispatch:
    inputs:
      url:
        description: "Base URL"
        required: true
        default: "https://test-dispatch.com"

jobs:
  featuretests:
    runs-on: ubuntu-latest
    env:
      CI: true
      DEFAULT_URL: "https://test.com"
    steps:
      - name: Set the variables
        env:
          DEFAULT_URL: 'https://test.com' # here is the default message
        run: echo "MESSAGE=${{ github.event.inputs.url || env.DEFAULT_URL }}" >> $GITHUB_ENV

      - name: Print some text
        run: echo "$MESSAGE" # prints the environmental variable, MESSAGE
