on:
  workflow_dispatch:
    inputs:
      url:
        description: "Base URL"
        required: true
        default: "https://test.com"

jobs:
  featuretests:
    runs-on: ubuntu-latest
    env:
      CI: true
      DEFAULT_URL: "https://test.com"
    steps:
      - name: Determine Base URL
        if: 1 == 1
        run: echo "WORKS"